disabled_rules:
 - trailing_comma
 - trailing_whitespace
 - todo
 - multiple_closures_with_trailing_closure
 - unused_capture_list
 - comment_spacing
 - inclusive_language
 - identifier_name
 - cyclomatic_complexity

function_parameter_count: 8

vertical_whitespace:
  max_empty_lines: 2

line_length:
  warning: 300
  error: 400
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  
switch_case_alignment:
  indented_cases: true
  
identifier_name:
    excluded: id

function_body_length: 80
type_body_length: 400
